Parameters:
  VpcId: # Also, this will be the name of the EC2 instance and multiple ofhter AWS resources.
    Type: String
    Description: The VpcId to deploy the SQL Instances
    Default: "Workshop - .NET development on AWS"

  VpcCidr: # Also, this will be the name of the EC2 instance and multiple ofhter AWS resources.
    Type: String
    Description: The VpcId CIDR

  SubnetIds: # "+TheStrong1" is appended by the system.
    Type: CommaDelimitedList
    Description: "The Subnet IDs to deploy the database instances"
    Default: "1,2,3"
    #AllowedPattern: "^\\S{6,}$"

Resources:
  ParameterGroup5E32DECB:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Parameter group for sqlserver-se-15.0
      Family: sqlserver-se-15.0
      Parameters:
        locks: "10000"
  SecurityGroupDD263621:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SqlStack/SecurityGroup
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: !Ref VpcCidr
          Description: Allow connection from the ec2
          FromPort: 1433
          IpProtocol: tcp
          ToPort: 1433
      VpcId: !Ref VpcId
  DatabaseSubnetGroup7D60F180:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Database database
      SubnetIds: !Ref SubnetIds
  DatabaseSecret3B817195:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Join
        - ""
        - - "Generated by the CDK for stack: "
          - !Ref "AWS::StackName"
      GenerateSecretString:
        ExcludeCharacters: ' %+~`#$&*()|[]{}:;<>?!''/@"\'
        GenerateStringKey: password
        PasswordLength: 30
        SecretStringTemplate: '{"username":"admin"}'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  DatabaseSecretAttachmentE5D1B020:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref "DatabaseSecret3B817195"
      TargetId: !Ref "DatabaseB269D8BB"
      TargetType: AWS::RDS::DBInstance
  DatabaseB269D8BB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.xlarge
      AllocatedStorage: "100"
      CopyTagsToSnapshot: true
      DBParameterGroupName: !Ref "ParameterGroup5E32DECB"
      DBSubnetGroupName: !Ref "DatabaseSubnetGroup7D60F180"
      Engine: sqlserver-se
      LicenseModel: license-included
      MasterUsername: !Join
        - ""
        - - "{{resolve:secretsmanager:"
          - !Ref "DatabaseSecret3B817195"
          - :SecretString:username::}}
      MasterUserPassword: !Join
        - ""
        - - "{{resolve:secretsmanager:"
          - !Ref "DatabaseSecret3B817195"
          - :SecretString:password::}}
      MultiAZ: false
      StorageType: gp2
      VPCSecurityGroups:
        - !GetAtt "SecurityGroupDD263621.GroupId"
    UpdateReplacePolicy: Snapshot
    DeletionPolicy: Snapshot
